CREATE TABLE invoices (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id NUMBER NOT NULL,
    invoice_number VARCHAR2(50) UNIQUE NOT NULL,
    total_amount NUMBER(10,2) NOT NULL,
    issued_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_invoice_payment FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
);