CREATE TABLE notifications (
    notification_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    message VARCHAR2(255) NOT NULL,
    status VARCHAR2(20) DEFAULT 'SENT',
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id)
        REFERENCES users(user_id)
);