CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id NUMBER NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    status VARCHAR2(20) DEFAULT 'PENDING',
    payment_date DATE,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_payment_subscription FOREIGN KEY (subscription_id)
        REFERENCES subscriptions(subscription_id)
);