CREATE TABLE subscriptions (
    subscription_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    plan_id NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    start_date DATE,
    next_payment_date DATE,
    created_at DATE DEFAULT SYSDATE,
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_plan FOREIGN KEY (plan_id)
        REFERENCES plans(plan_id)
); 