CREATE TABLE subscription_history (
    history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id NUMBER NOT NULL,
    old_plan_id NUMBER,
    new_plan_id NUMBER,
    changed_at DATE DEFAULT SYSDATE,
    changed_by VARCHAR2(100),
    CONSTRAINT fk_history_subscription FOREIGN KEY (subscription_id)
        REFERENCES subscriptions(subscription_id),
    CONSTRAINT fk_history_old_plan FOREIGN KEY (old_plan_id)
        REFERENCES plans(plan_id),
    CONSTRAINT fk_history_new_plan FOREIGN KEY (new_plan_id)
        REFERENCES plans(plan_id)
);